sudo: false

language: python

python:
   - "3.6"

before_install:
    - cat .travis.yml
    # - pip install --upgrade pip
    # - pip --version
    - sudo apt-get install docker.io
    - npm update -g
    - sudo apt-get update
    - sudo apt-get install google-chrome-stable
    - make gui_testing
    - chmod +x react/__tests__/linux_chrome

install:
    - npm install -g istanbul
    - npm install -g jshint
    - npm install -g mocha
    - npm install lodash
    - npm install newman
    - pip install mypy
    - pip install numpy
    - pip install requests
    - pip list
    - pip psycog2

before_script:
    - date
    - uname -a
    # - printenv | sort
    # - autopep8  --version
    # - coverage  --version
    # - git       --version
    # - make      --version
    # - mypy      --version
    # - pydoc     --version
    # - pylint    --version
    # - python3.6 --version
    # - ls -al
    # - cat makefile
    #- chmod 777 RunCollatz.py
    #- cat projects/collatz/makefile

script:
   - node_modules/.bin/newman run postman_tests.json -g postman_globals.json
   - python backend/tests.py
   - make travis
