sudo: false

language: python

python:
   - "3.6"

addons:
  chrome: stable

before_install:
    - cat .travis.yml
    - pip install --upgrade pip
    - pip --version
    - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/build/iambrandonchan/learning2earn/react/__tests__/

install:
    - pip install autopep8
    - pip install coverage
    - pip install mypy
    - pip install pylint
    - pip install numpy
    - pip install selenium
    - pip install pyvirtualdisplay
    - pip list

before_script:
    - date
    - uname -a
    - printenv | sort
    - autopep8  --version
    - coverage  --version
    - git       --version
    - make      --version
    - mypy      --version
    - pydoc     --version
    - pylint    --version
    - python3.6 --version
    - ls -al
    - cat makefile

script:
    - make travis